version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    entrypoint: v2ray run -config=/etc/v2ray/config.json
  
  caddy:
    image: caddy:2.6-alpine
    container_name: caddy
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - WSPATH=${WSPATH}
    ports:
      - ${HTTPPORT:-80}:80
      - ${HTTPSPORT:-443}:443
    volumes:
      - ./caddy/Caddyfile:/Caddyfile:ro
      - ./caddy/index.html:/site/index.html
    entrypoint: [caddy,run,--config,/Caddyfile]
