version: '3'

services:
  agh:
    image: adguard/adguardhome
    container_name: agh
    restart: always
    volumes:
      - ./agh/work:/opt/adguardhome/work
      - ./agh/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - npm_default
      
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    volumes:
      - ./coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
    networks:
      - npm_default

networks:
  npm_default:
    external: true
