version: '3'

services:
  agh:
    image: adguard/adguardhome
    container_name: agh
    restart: always
    volumes:
      - ./agh/work:/opt/adguardhome/work
      - ./agh/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
        npm_default:
          ipv4_address: 192.168.233.31
      
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    volumes:
      - ./coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
    networks:
        npm_default:
          ipv4_address: 192.168.233.32

networks:
  npm_default:
    external: true
