version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core:v5.2.1
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - 127.0.0.1:55555:55555
    entrypoint: v2ray run -config=/etc/v2ray/config.json