version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core:v5.2.1
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    networks:
        npm_default:
          ipv4_address: 192.168.233.41
    entrypoint: v2ray run -config=/etc/v2ray/config.json
  
  v2ray-caddy:
    image: caddy:2.6-alpine
    container_name: v2ray-caddy
    restart: always
    volumes:
      - ./caddy/Caddyfile:/Caddyfile:ro
      - ./caddy/index.html:/site/index.html
    networks:
        npm_default:
          ipv4_address: 192.168.233.42
    entrypoint: [caddy,run,--config,/Caddyfile]


networks:
  npm_default:
    external: true
