version: '3'
services:
  derp:
    build: .
    restart: always
    ports:
      - "3478:3478/udp"
    volumes:
      - "/var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock"
    networks:
      - npm_default

networks:
  npm_default:
    external: true
