version: '3'

services:
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    volumes:
      - ./coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
  
  caddy:
    image: caddy:2.6-alpine
    container_name: coredns-caddy
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - ${HTTPPORT:-80}:80
      - ${HTTPSPORT:-443}:443
    volumes:
      - ./caddy/Caddyfile:/Caddyfile:ro
    entrypoint: [caddy,run,--config,/Caddyfile]
