version: '3'

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt
    ports:
        - '127.0.0.1:81:81'
        - '23443:443'
    networks:
        default:
          ipv4_address: 192.168.233.11
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.233.0/24